"""Postgres is selected only when a DSN is passed. Local tests stay on SQLite.

Run the SQLite suite (no Neon required):

    pytest

Run this Postgres suite against a reachable server:

    BANDROS_TEST_POSTGRES=postgresql://USER:PASS@127.0.0.1:5432/DB pytest tests/test_postgres_store.py
"""

from __future__ import annotations

from datetime import timedelta
import os
from pathlib import Path
from uuid import uuid4

import pytest

from apps.api.app.database import ADDITIVE_COLUMNS, SCHEMA, Database
from apps.api.app.postgres_store import postgres_ddl, schema_for_path, translate_sql
from apps.api.app.repository import QUEUE_EXPIRY
from apps.api.app.tenancy import tenant_locations


def test_sqlite_ignores_an_ambient_database_url(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("DATABASE_URL", "postgresql://user:pass@example/db")
    database = Database(tmp_path / "local.db")
    database.initialize()
    assert database.postgres is False
    assert database.path.is_file()


def test_schema_names_fit_postgres_and_isolate_accounts(tmp_path: Path) -> None:
    first = tenant_locations("acct_a", tmp_path, tmp_path / "files")[0]
    second = tenant_locations("acct_b", tmp_path, tmp_path / "files")[0]
    default = schema_for_path(tmp_path / "workspace.db")
    assert default == "app"
    assert schema_for_path(first) != schema_for_path(second)
    assert len(schema_for_path(first)) <= 63
    assert schema_for_path(first).startswith("t")


def test_postgres_ddl_covers_app_tables_and_identity_columns() -> None:
    ddl = postgres_ddl(SCHEMA)
    for table in (
        "bots",
        "conversations",
        "messages",
        "runs",
        "run_events",
        "approvals",
        "memories",
        "skills",
        "bot_skills",
        "jobs",
        "work_groups",
        "group_members",
        "group_messages",
        "group_run_links",
        "plugins",
        "group_queue",
        "handoffs",
        "tool_calls",
        "chatgpt_oauth",
        "oauth_transactions",
        "workspace_meta",
    ):
        assert f"CREATE TABLE IF NOT EXISTS {table}" in ddl
    assert "AUTOINCREMENT" not in ddl
    assert "PRAGMA" not in ddl
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "heartbeat_at" in ADDITIVE_COLUMNS["runs"]


def test_sql_translation_keeps_literals_and_conflicts() -> None:
    assert translate_sql("BEGIN IMMEDIATE") == ""
    assert translate_sql("UPDATE runs SET prompt = ? WHERE id = ?") == "UPDATE runs SET prompt = %s WHERE id = %s"
    assert (
        translate_sql("INSERT OR IGNORE INTO group_members VALUES (?, ?)")
        == "INSERT INTO group_members VALUES (%s, %s) ON CONFLICT DO NOTHING"
    )
    assert translate_sql("DELETE FROM messages WHERE content LIKE '[Grup %'") == (
        "DELETE FROM messages WHERE content LIKE '[Grup %%'"
    )
    queued = translate_sql(
        "INSERT INTO group_queue (group_id, bot_id) VALUES (?, ?) ON CONFLICT (group_id, bot_id) DO NOTHING"
    )
    assert queued.count("ON CONFLICT") == 1
    assert "%s" in queued
    event = translate_sql("INSERT INTO run_events (run_id, type, payload, created_at) VALUES (?, ?, ?, ?)")
    assert event.endswith("RETURNING id")


def test_queue_expiry_is_ten_minutes() -> None:
    assert QUEUE_EXPIRY == timedelta(minutes=10)


@pytest.mark.skipif(not os.environ.get("BANDROS_TEST_POSTGRES"), reason="BANDROS_TEST_POSTGRES is not set")
def test_postgres_accounts_do_not_share_rows(tmp_path: Path) -> None:
    from apps.api.app.repository import Repository

    url = os.environ["BANDROS_TEST_POSTGRES"]
    first_path = tenant_locations(f"acct-{uuid4()}", tmp_path, tmp_path / "files")[0]
    second_path = tenant_locations(f"acct-{uuid4()}", tmp_path, tmp_path / "files")[0]
    first = Database(first_path, database_url=url)
    second = Database(second_path, database_url=url)
    first.initialize()
    second.initialize()
    Repository(first).create_bot("OnlyA", "", "", None)
    assert [bot.name for bot in Repository(second).list_bots()] == []


@pytest.mark.skipif(not os.environ.get("BANDROS_TEST_POSTGRES"), reason="BANDROS_TEST_POSTGRES is not set")
def test_postgres_queued_expiry_and_single_writer(tmp_path: Path) -> None:
    import threading
    from datetime import UTC, datetime, timedelta

    from apps.api.app.domain import RunStatus
    from apps.api.app.repository import ORPHAN_NOTICE, Repository
    from apps.api.app.runtime import RunRuntime

    url = os.environ["BANDROS_TEST_POSTGRES"]
    path = tenant_locations(f"acct-{uuid4()}", tmp_path, tmp_path / "files")[0]
    database = Database(path, database_url=url)
    database.initialize()
    repository = Repository(database)
    bot = repository.create_bot("Bandros", "", "", None)
    group = repository.create_group("QA", "", [bot.id])
    conversation_id = repository.conversation_for_bot(bot.id)
    run = repository.create_run(bot.id, conversation_id, "kerja", "test-model")
    repository.link_run_to_group(run.id, group.id)
    assert repository.enqueue_group_speaker(group.id, bot.id, "kerja", None, 0) is True
    assert repository.enqueue_group_speaker(group.id, bot.id, "kerja", None, 0) is False
    event = repository.record_event(run.id, "run.queued", {})
    assert event.id > 0

    stale = (datetime.now(UTC) - timedelta(minutes=10, seconds=5)).isoformat()
    with repository.database.connection() as db:
        db.execute("UPDATE runs SET created_at = ? WHERE id = ?", (stale, str(run.id)))
        db.execute("UPDATE group_queue SET created_at = ?", (stale,))
    stranger = RunRuntime(repository, None, "test-model", 1)  # type: ignore[arg-type]
    assert stranger.reconcile_runs() == 1
    assert repository.get_run(run.id).status is RunStatus.FAILED
    assert repository.get_run(run.id).error == ORPHAN_NOTICE
    assert repository.queued_bot_ids(group.id) == []

    fresh = repository.create_run(bot.id, conversation_id, "lagi", "test-model")
    assert repository.update_run(fresh.id, RunStatus.RUNNING, expect=RunStatus.QUEUED) is True
    assert repository.commit_assistant_turn(fresh.id, "jawaban", "test-model") is True
    assert repository.list_messages(conversation_id)[-1].content == "jawaban"

    barrier = threading.Barrier(2)
    results: list[bool] = []
    raced = repository.create_run(bot.id, conversation_id, "balapan", "test-model")
    assert repository.update_run(raced.id, RunStatus.RUNNING, expect=RunStatus.QUEUED) is True

    def finish() -> None:
        barrier.wait()
        results.append(repository.update_run(raced.id, RunStatus.COMPLETED, expect=RunStatus.RUNNING))

    threads = [threading.Thread(target=finish) for _ in range(2)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()
    assert sorted(results) == [False, True]
    skill = repository.create_skill("notes", "Notes", "Keep notes.")
    repository.assign_skill(bot.id, skill.id)
    assert [item.name for item in repository.list_bot_skills(bot.id)] == ["notes"]
    repository.save_chatgpt_connection("client", "host", None, "token", None, None, "sub", "a@example.test", None, "openid")
    assert repository.chatgpt_connection()["email"] == "a@example.test"
    repository.delete_bot(bot.id)
    assert repository.list_bots() == []


@pytest.mark.skipif(not os.environ.get("BANDROS_TEST_POSTGRES"), reason="BANDROS_TEST_POSTGRES is not set")
def test_two_postgres_connections_share_one_schema(tmp_path: Path) -> None:
    from apps.api.app.domain import RunStatus
    from apps.api.app.repository import Repository

    url = os.environ["BANDROS_TEST_POSTGRES"]
    path = tenant_locations(f"acct-{uuid4()}", tmp_path, tmp_path / "files")[0]
    first = Database(path, database_url=url)
    second = Database(path, database_url=url)
    first.initialize()
    second.initialize()
    repository = Repository(first)
    bot = repository.create_bot("Bandros", "", "", None)
    other = Repository(second)
    assert [item.name for item in other.list_bots()] == ["Bandros"]
    run = repository.create_run(bot.id, repository.conversation_for_bot(bot.id), "kerja", "test-model")
    assert repository.update_run(run.id, RunStatus.RUNNING, expect=RunStatus.QUEUED) is True
    assert other.update_run(run.id, RunStatus.COMPLETED, expect=RunStatus.RUNNING) is True
    assert repository.update_run(run.id, RunStatus.FAILED, "late", expect=RunStatus.RUNNING) is False
    assert other.get_run(run.id).status is RunStatus.COMPLETED
