"""Postgres (Neon) storage for multi-instance Vercel.

SQLite stays the local default. When DATABASE_URL is passed in, every tenant
uses its own schema in that database so concurrent instances share one DSN
without sharing rows. Statements stay in the sqlite `?` style; this module
translates them per connection.
"""

from __future__ import annotations

from contextlib import contextmanager
from datetime import UTC, datetime
import hashlib
import re
from pathlib import Path
from typing import Any, Iterator

import psycopg
from psycopg.rows import dict_row

_HEX_DIGEST = re.compile(r"[0-9a-f]{64}")
_SCHEMA_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]{0,62}")
_INSERT_OR_IGNORE = re.compile(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.IGNORECASE)
_BEGIN = re.compile(r"^\s*BEGIN\b", re.IGNORECASE)
_RETURNING_ID = re.compile(r"\bINSERT\s+INTO\s+run_events\b", re.IGNORECASE)


def schema_for_path(path: Path) -> str:
    """One schema per ChatGPT account. Postgres identifiers max out at 63 bytes."""
    parts = path.parts
    if "users" in parts:
        index = parts.index("users")
        if index + 1 < len(parts):
            digest = parts[index + 1].lower()
            if _HEX_DIGEST.fullmatch(digest):
                return "t" + digest[:62]
    return "app"


def translate_sql(sql: str) -> str:
    """Turn sqlite-shaped SQL into something Postgres will run."""
    if _BEGIN.match(sql):
        return ""
    rewritten = _INSERT_OR_IGNORE.sub("INSERT INTO", sql)
    needs_do_nothing = rewritten != sql and "ON CONFLICT" not in rewritten.upper()
    chars: list[str] = []
    for char in rewritten:
        if char == "%":
            chars.append("%%")
        elif char == "?":
            chars.append("%s")
        else:
            chars.append(char)
    statement = "".join(chars).strip()
    if needs_do_nothing:
        statement = statement.rstrip(";") + " ON CONFLICT DO NOTHING"
    if _RETURNING_ID.match(statement) and "RETURNING" not in statement.upper():
        statement = statement.rstrip(";") + " RETURNING id"
    return statement


def postgres_ddl(sqlite_schema: str) -> str:
    ddl = sqlite_schema.replace("PRAGMA foreign_keys = ON;\n", "")
    return ddl.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )


def migrate_postgres(
    database_url: str,
    schema: str,
    sqlite_schema: str,
    additive_columns: dict[str, dict[str, str]],
) -> None:
    """Create the tenant schema and apply additive column migrations."""
    quoted = _quote_schema(schema)
    lock_key = _lock_key(schema)
    with _connect(database_url, autocommit=True) as conn:
        conn.execute(f"CREATE SCHEMA IF NOT EXISTS {quoted}")
    with _connect(database_url, autocommit=False) as conn:
        with conn.transaction():
            conn.execute("SELECT pg_advisory_xact_lock(%s)", (lock_key,))
            conn.execute(f"SET LOCAL search_path TO {quoted}")
            _apply_ddl(conn, postgres_ddl(sqlite_schema))
            _add_columns(conn, additive_columns)
            _ensure_group_queue_uniqueness(conn)
            _ensure_member_rowid(conn)
            _record_migration(conn, "001_workspace")


@contextmanager
def postgres_connection(database_url: str, schema: str) -> Iterator[Any]:
    quoted = _quote_schema(schema)
    with _connect(database_url, autocommit=False) as conn:
        with conn.transaction():
            conn.execute(f"SET LOCAL search_path TO {quoted}")
            yield _PostgresConnection(conn)


class _Result:
    def __init__(self, rows: list[dict[str, Any]], rowcount: int, lastrowid: int | None = None) -> None:
        self._rows = rows
        self.rowcount = rowcount
        self.lastrowid = lastrowid

    def fetchone(self) -> dict[str, Any] | None:
        if not self._rows:
            return None
        return self._rows.pop(0)

    def fetchall(self) -> list[dict[str, Any]]:
        rows = self._rows
        self._rows = []
        return rows


class _PostgresConnection:
    def __init__(self, connection: psycopg.Connection[dict[str, Any]]) -> None:
        self._connection = connection

    def execute(self, sql: str, params: Any = None) -> _Result:
        statement = translate_sql(sql)
        if not statement:
            return _Result([], 0)
        cursor = self._connection.execute(statement, params if params is not None else ())
        rowcount = cursor.rowcount
        rows: list[dict[str, Any]] = []
        if cursor.description is not None:
            rows = list(cursor.fetchall())
        lastrowid = None
        if " RETURNING id" in statement and rows:
            lastrowid = int(rows[0]["id"])
            rows = []
        return _Result(rows, rowcount, lastrowid)

    def executemany(self, sql: str, params: Any) -> _Result:
        statement = translate_sql(sql)
        if not statement:
            return _Result([], 0)
        with self._connection.cursor() as cursor:
            cursor.executemany(statement, params)
            return _Result([], cursor.rowcount)


def _connect(database_url: str, *, autocommit: bool) -> psycopg.Connection[dict[str, Any]]:
    # prepare_threshold=None keeps Neon/PgBouncer transaction pooling from
    # reusing a prepared statement on the wrong server connection.
    return psycopg.connect(
        database_url,
        autocommit=autocommit,
        prepare_threshold=None,
        connect_timeout=15,
        row_factory=dict_row,
    )


def _quote_schema(schema: str) -> str:
    if not _SCHEMA_NAME.fullmatch(schema):
        raise ValueError("invalid postgres schema")
    return f'"{schema}"'


def _lock_key(schema: str) -> int:
    digest = hashlib.sha256(b"bandros-migrate:" + schema.encode()).digest()
    return int.from_bytes(digest[:8], "big", signed=True)


def _apply_ddl(connection: psycopg.Connection[dict[str, Any]], ddl: str) -> None:
    for statement in _statements(ddl):
        connection.execute(statement)


def _statements(ddl: str) -> list[str]:
    statements: list[str] = []
    for chunk in ddl.split(";"):
        statement = chunk.strip()
        if not statement or statement.upper().startswith("PRAGMA"):
            continue
        statements.append(statement)
    return statements


def _add_columns(
    connection: psycopg.Connection[dict[str, Any]],
    additive_columns: dict[str, dict[str, str]],
) -> None:
    for table, columns in additive_columns.items():
        present = _column_names(connection, table)
        for name, definition in columns.items():
            if name in present:
                continue
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
                raise ValueError("invalid column")
            connection.execute(f"ALTER TABLE {table} ADD COLUMN {name} {definition}")


def _column_names(connection: psycopg.Connection[dict[str, Any]], table: str) -> set[str]:
    rows = connection.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = %s
        """,
        (table,),
    ).fetchall()
    return {str(row["column_name"]) for row in rows}


def _ensure_member_rowid(connection: psycopg.Connection[dict[str, Any]]) -> None:
    """SQLite orders members by the implicit rowid. Postgres needs a real column."""
    if "group_members" not in _table_names(connection):
        return
    if "rowid" in _column_names(connection, "group_members"):
        return
    connection.execute("ALTER TABLE group_members ADD COLUMN rowid BIGINT GENERATED BY DEFAULT AS IDENTITY")


def _ensure_group_queue_uniqueness(connection: psycopg.Connection[dict[str, Any]]) -> None:
    if "group_queue" not in _table_names(connection):
        return
    connection.execute(
        """
        DELETE FROM group_queue
        WHERE id NOT IN (
            SELECT MIN(id) FROM group_queue GROUP BY group_id, bot_id
        )
        """
    )
    connection.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS group_queue_group_bot ON group_queue (group_id, bot_id)"
    )


def _table_names(connection: psycopg.Connection[dict[str, Any]]) -> set[str]:
    rows = connection.execute(
        """
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = current_schema()
        """
    ).fetchall()
    return {str(row["table_name"]) for row in rows}


def _record_migration(connection: psycopg.Connection[dict[str, Any]], version: str) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version TEXT PRIMARY KEY,
            applied_at TEXT NOT NULL
        )
        """
    )
    connection.execute(
        """
        INSERT INTO schema_migrations (version, applied_at) VALUES (%s, %s)
        ON CONFLICT (version) DO NOTHING
        """,
        (version, datetime.now(UTC).isoformat()),
    )
